### ISSUE TITLE
如需添加Mac支持，需要做些什么？

### ISSUE THREAD

**Issue by xiamubobby** [RationalityFrontline/jxtp#1]
我这边有环境可以负责，不过需要一些指导，按照Linux的building流程，同时添加中泰SDK里的*.dynalib到对应路径是无法完成构建的。
complaining about missing jxtp.h
以及一些其他问题。（比如jni目录缺少对mac所需头文件的支持）

**Comment by xiamubobby** [comment]
(jxtp) uname@MacbookPro jxtp % ./build.sh
cd swig
./build.sh
mkdir: ../java/src/main/java/org/rationalityfrontline: No such file or directory
rm: ../cpp/src/jxtp.cpp: No such file or directory
rm: ../cpp/src/jxtp.h: No such file or directory
Unable to open file ../java/src/main/java/org/rationalityfrontline/jxtp/XTP_LOG_LEVEL.java: No such file or directory
cd ../cpp
./build.sh
-- The C compiler identification is AppleClang 12.0.0.12000032
-- The CXX compiler identification is AppleClang 12.0.0.12000032
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
CMake Error at src/CMakeLists.txt:25 (add_library):
  Cannot find source file:

    jxtp.h

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .h .hh .h++
  .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .ispc


CMake Error at src/CMakeLists.txt:25 (add_library):
  No SOURCES given to target: jxtp


CMake Generate step failed.  Build files cannot be regenerated correctly.
make: Makefile: No such file or directory
make: *** No rule to make target `Makefile'.  Stop.
cp: build/lib/libjxtp.so: No such file or directory
set +v
请移除上面显示 error 的所有行数处的代码后（共4行），按任意键继续

**Comment by xiamubobby** [comment]
./build.sh
-- The C compiler identification is AppleClang 12.0.0.12000032
-- The CXX compiler identification is AppleClang 12.0.0.12000032
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
CMake Error at src/CMakeLists.txt:25 (add_library):
  Cannot find source file:

    jxtp.h

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .h .hh .h++
  .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .ispc


CMake Error at src/CMakeLists.txt:25 (add_library):
  No SOURCES given to target: jxtp


CMake Generate step failed.  Build files cannot be regenerated correctly.
make: Makefile: No such file or directory
make: *** No rule to make target `Makefile'.  Stop.
cp: build/lib/libjxtp.so: No such file or directory
cd ../java
./gradlew jar
> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> java.io.FileNotFoundException: ～/IdeaProjects/jxtp/java/src/main/java/org/rationalityfrontline/jxtp/jxtpJNI.java (No such file or directory)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 694ms
1 actionable task: 1 executed

**Comment by xiamubobby** [comment]
![image](https://i.ibb.co/27MR6YS/WX20210421-034408-2x.png)

**Comment by RationalityFrontline** [comment]
要实现 MAC 下的构建，需要做以下步骤：
1. 在 ./cpp/include/ 目录下添加 MAC 下的 jni.h 以及 jni_md.h
2. 修改 ./cpp/src/CMakeLists.txt 中的内容来在 MAC 下使用上面加入的 jni 头文件
3. 在 .lib/ 目录下添加 XTP 的 .dylib 文件
4. 仿照 Linux 下的 build.sh 编写 MAC 版本的 build script

我已经新建了一个名为 mac 的 [branch](https://github.com/RationalityFrontline/jxtp/tree/mac)，里面已经帮你做好了步骤 1~3，你需要自己实现步骤 4。
从你发的错误日志里可以看出，你的 SWIG 构建过程失败了，因此没有生成 jxtp.h 文件。

**Comment by xiamubobby** [comment]
非常感谢，我开始尝试了。

稍微改了下swig的build脚本，现在到下一阶段了。
但编译cpp过程中产生了一些问题，想先问下这个问题和cpp本身的情况有关吗，如果你在其他平台上确定没问题话，我再去XCode层面检查。
因为确实没看到这些symbol的declaration，我手头因为没有好的Linux/Win运行时，因此也没法验证pipeline在那两个平台上的可用性：

------

(jxtp) uname@MacBookPro jxtp % ./build.sh
cd swig
./build.sh
rm: ../cpp/src/jxtp.cpp: No such file or directory
rm: ../cpp/src/jxtp.h: No such file or directory
../cpp/src/xtp_quote_api.h:37: Warning 514: Director base class XTP::API::QuoteSpi has no virtual destructor.
../cpp/src/xtp_trader_api.h:38: Warning 514: Director base class XTP::API::TraderSpi has no virtual destructor.
cd ../cpp
./build.sh
-- The C compiler identification is AppleClang 12.0.0.12000032
-- The CXX compiler identification is AppleClang 12.0.0.12000032
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: ～/IdeaProjects/INTJers/jxtp/cpp/build
[ 50%] Building CXX object src/CMakeFiles/jxtp.dir/jxtp.cpp.o
～/IdeaProjects/INTJers/jxtp/cpp/src/jxtp.cpp:26479:38: error: use of undeclared identifier 'jarr3'; did you mean 'arg3'?
  SWIG_JavaArrayArgoutLonglong(jenv, jarr3, (long long *)arg3, jarg3); 
                                     ^~~~~
                                     arg3
～/IdeaProjects/INTJers/jxtp/cpp/src/jxtp.cpp:26455:12: note: 'arg3' declared here
  int64_t *arg3 ;
           ^
～/IdeaProjects/INTJers/jxtp/cpp/src/jxtp.cpp:26480:38: error: use of undeclared identifier 'jarr6'; did you mean 'arg6'?
  SWIG_JavaArrayArgoutLonglong(jenv, jarr6, (long long *)arg6, jarg6); 
                                     ^~~~~
                                     arg6
～/IdeaProjects/INTJers/jxtp/cpp/src/jxtp.cpp:26458:12: note: 'arg6' declared here
  int64_t *arg6 ;
           ^
～/IdeaProjects/INTJers/jxtp/cpp/src/jxtp.cpp:26517:38: error: use of undeclared identifier 'jarr3'; did you mean 'arg3'?
  SWIG_JavaArrayArgoutLonglong(jenv, jarr3, (long long *)arg3, jarg3); 
                                     ^~~~~
                                     arg3
～/IdeaProjects/INTJers/jxtp/cpp/src/jxtp.cpp:26493:12: note: 'arg3' declared here
  int64_t *arg3 ;
           ^
～/IdeaProjects/INTJers/jxtp/cpp/src/jxtp.cpp:26518:38: error: use of undeclared identifier 'jarr6'; did you mean 'arg6'?
  SWIG_JavaArrayArgoutLonglong(jenv, jarr6, (long long *)arg6, jarg6); 
                                     ^~~~~
                                     arg6
～/IdeaProjects/INTJers/jxtp/cpp/src/jxtp.cpp:26496:12: note: 'arg6' declared here
  int64_t *arg6 ;
           ^
4 errors generated.
make[2]: *** [src/CMakeFiles/jxtp.dir/jxtp.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/jxtp.dir/all] Error 2
make: *** [all] Error 2
cp: build/lib/libjxtp.so: No such file or directory
set +v
请移除上面显示 error 的所有行数处的代码后（共4行），按任意键继续^C

**Comment by xiamubobby** [comment]
我换用了Linux build也无法通过，需要确定下这个代码版本的building过程一定是可以work的吗？
---
runtime (ArchLinux on Docker on Mac via Docker Desktop):

sh-5.1# uname -s
Linux
sh-5.1# uname -r
5.10.25-linuxkit
sh-5.1# uname -v
#1 SMP Tue Mar 23 09:27:39 UTC 2021
---

-- The C compiler identification is GNU 10.2.0
-- The CXX compiler identification is GNU 10.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/sbin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/sbin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /mac/home/IdeaProjects/INTJers/jxtp/cpp/build
[ 50%] Building CXX object src/CMakeFiles/jxtp.dir/jxtp.cpp.o
cd ../cpp
./build.sh
/mac/home/IdeaProjects/INTJers/jxtp/cpp/src/jxtp.cpp: In member function ‘virtual void SwigDirector_QuoteSpi::OnDepthMarketData(XTPMD*, int64_t*, int32_t, int32_t, int64_t*, int32_t, int32_t)’:
/mac/home/IdeaProjects/INTJers/jxtp/cpp/src/jxtp.cpp:1518:58: warning: invalid conversion from ‘int64_t*’ {aka ‘long int*’} to ‘const jlong*’ {aka ‘const long long int*’} [-fpermissive]
 1518 |       jenv->SetLongArrayRegion(jbid1_qty, 0, bid1_count, bid1_qty);
      |                                                          ^~~~~~~~
      |                                                          |
      |                                                          int64_t* {aka long int*}
In file included from /mac/home/IdeaProjects/INTJers/jxtp/cpp/src/jxtp.cpp:179:
/mac/home/IdeaProjects/INTJers/jxtp/cpp/src/../include/linux/jni.h:1789:42: note:   initializing argument 4 of ‘void JNIEnv_::SetLongArrayRegion(jlongArray, jsize, jsize, const jlong*)’
 1789 |                             const jlong *buf) {
      |                             ~~~~~~~~~~~~~^~~
/mac/home/IdeaProjects/INTJers/jxtp/cpp/src/jxtp.cpp:1523:58: warning: invalid conversion from ‘int64_t*’ {aka ‘long int*’} to ‘const jlong*’ {aka ‘const long long int*’} [-fpermissive]
 1523 |       jenv->SetLongArrayRegion(jask1_qty, 0, ask1_count, ask1_qty);
      |                                                          ^~~~~~~~
      |                                                          |
      |                                                          int64_t* {aka long int*}
In file included from /mac/home/IdeaProjects/INTJers/jxtp/cpp/src/jxtp.cpp:179:
/mac/home/IdeaProjects/INTJers/jxtp/cpp/src/../include/linux/jni.h:1789:42: note:   initializing argument 4 of ‘void JNIEnv_::SetLongArrayRegion(jlongArray, jsize, jsize, const jlong*)’
 1789 |                             const jlong *buf) {
      |                             ~~~~~~~~~~~~~^~~
/mac/home/IdeaProjects/INTJers/jxtp/cpp/src/jxtp.cpp:1533:60: warning: invalid conversion from ‘int64_t*’ {aka ‘long int*’} to ‘jlong*’ {aka ‘long long int*’} [-fpermissive]
 1533 |       (jenv)->GetLongArrayRegion(jbid1_qty, 0, bid1_count, bid1_qty);
      |                                                            ^~~~~~~~
      |                                                            |
      |                                                            int64_t* {aka long int*}
In file included from /mac/home/IdeaProjects/INTJers/jxtp/cpp/src/jxtp.cpp:179:
/mac/home/IdeaProjects/INTJers/jxtp/cpp/src/../include/linux/jni.h:1756:60: note:   initializing argument 4 of ‘void JNIEnv_::GetLongArrayRegion(jlongArray, jsize, jsize, jlong*)’
 1756 |                             jsize start, jsize len, jlong *buf) {
      |                                                     ~~~~~~~^~~
/mac/home/IdeaProjects/INTJers/jxtp/cpp/src/jxtp.cpp:1536:60: warning: invalid conversion from ‘int64_t*’ {aka ‘long int*’} to ‘jlong*’ {aka ‘long long int*’} [-fpermissive]
 1536 |       (jenv)->GetLongArrayRegion(jask1_qty, 0, ask1_count, ask1_qty);
      |                                                            ^~~~~~~~
      |                                                            |
      |                                                            int64_t* {aka long int*}
In file included from /mac/home/IdeaProjects/INTJers/jxtp/cpp/src/jxtp.cpp:179:
/mac/home/IdeaProjects/INTJers/jxtp/cpp/src/../include/linux/jni.h:1756:60: note:   initializing argument 4 of ‘void JNIEnv_::GetLongArrayRegion(jlongArray, jsize, jsize, jlong*)’
 1756 |                             jsize start, jsize len, jlong *buf) {
      |                                                     ~~~~~~~^~~
/mac/home/IdeaProjects/INTJers/jxtp/cpp/src/jxtp.cpp: In function ‘void Java_org_rationalityfrontline_jxtp_jxtpJNI_QuoteSpi_1OnDepthMarketData(JNIEnv*, jclass, jlong, jobject, jlong, jobject, jlongArray, jint, jlongArray, jint)’:
/mac/home/IdeaProjects/INTJers/jxtp/cpp/src/jxtp.cpp:26469:38: warning: invalid conversion from ‘jlong*’ {aka ‘long long int*’} to ‘int64_t*’ {aka ‘long int*’} [-fpermissive]
26469 |     arg3 = jenv->GetLongArrayElements(jarg3, NULL);
      |            ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~
      |                                      |
      |                                      jlong* {aka long long int*}
/mac/home/IdeaProjects/INTJers/jxtp/cpp/src/jxtp.cpp:26474:38: warning: invalid conversion from ‘jlong*’ {aka ‘long long int*’} to ‘int64_t*’ {aka ‘long int*’} [-fpermissive]
26474 |     arg6 = jenv->GetLongArrayElements(jarg6, NULL);
      |            ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~
      |                                      |
      |                                      jlong* {aka long long int*}
/mac/home/IdeaProjects/INTJers/jxtp/cpp/src/jxtp.cpp:26479:38: error: ‘jarr3’ was not declared in this scope; did you mean ‘jarg3’?
26479 |   SWIG_JavaArrayArgoutLonglong(jenv, jarr3, (long long *)arg3, jarg3);
      |                                      ^~~~~
      |                                      jarg3
/mac/home/IdeaProjects/INTJers/jxtp/cpp/src/jxtp.cpp:26480:38: error: ‘jarr6’ was not declared in this scope; did you mean ‘jarg6’?
26480 |   SWIG_JavaArrayArgoutLonglong(jenv, jarr6, (long long *)arg6, jarg6);
      |                                      ^~~~~
      |                                      jarg6
/mac/home/IdeaProjects/INTJers/jxtp/cpp/src/jxtp.cpp:26482:43: warning: invalid conversion from ‘int64_t*’ {aka ‘long int*’} to ‘jlong*’ {aka ‘long long int*’} [-fpermissive]
26482 |     jenv->ReleaseLongArrayElements(jarg3, arg3, 0);
      |                                           ^~~~
      |                                           |
      |                                           int64_t* {aka long int*}
In file included from /mac/home/IdeaProjects/INTJers/jxtp/cpp/src/jxtp.cpp:179:
/mac/home/IdeaProjects/INTJers/jxtp/cpp/src/../include/linux/jni.h:1720:42: note:   initializing argument 2 of ‘void JNIEnv_::ReleaseLongArrayElements(jlongArray, jlong*, jint)’
 1720 |                                   jlong *elems,
      |                                   ~~~~~~~^~~~~
/mac/home/IdeaProjects/INTJers/jxtp/cpp/src/jxtp.cpp:26485:43: warning: invalid conversion from ‘int64_t*’ {aka ‘long int*’} to ‘jlong*’ {aka ‘long long int*’} [-fpermissive]
26485 |     jenv->ReleaseLongArrayElements(jarg6, arg6, 0);
      |                                           ^~~~
      |                                           |
      |                                           int64_t* {aka long int*}
In file included from /mac/home/IdeaProjects/INTJers/jxtp/cpp/src/jxtp.cpp:179:
/mac/home/IdeaProjects/INTJers/jxtp/cpp/src/../include/linux/jni.h:1720:42: note:   initializing argument 2 of ‘void JNIEnv_::ReleaseLongArrayElements(jlongArray, jlong*, jint)’
 1720 |                                   jlong *elems,
      |                                   ~~~~~~~^~~~~
/mac/home/IdeaProjects/INTJers/jxtp/cpp/src/jxtp.cpp: In function ‘void Java_org_rationalityfrontline_jxtp_jxtpJNI_QuoteSpi_1OnDepthMarketDataSwigExplicitQuoteSpi(JNIEnv*, jclass, jlong, jobject, jlong, jobject, jlongArray, jint, jlongArray, jint)’:
/mac/home/IdeaProjects/INTJers/jxtp/cpp/src/jxtp.cpp:26507:38: warning: invalid conversion from ‘jlong*’ {aka ‘long long int*’} to ‘int64_t*’ {aka ‘long int*’} [-fpermissive]
26507 |     arg3 = jenv->GetLongArrayElements(jarg3, NULL);
      |            ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~
      |                                      |
      |                                      jlong* {aka long long int*}
/mac/home/IdeaProjects/INTJers/jxtp/cpp/src/jxtp.cpp:26512:38: warning: invalid conversion from ‘jlong*’ {aka ‘long long int*’} to ‘int64_t*’ {aka ‘long int*’} [-fpermissive]
26512 |     arg6 = jenv->GetLongArrayElements(jarg6, NULL);
      |            ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~
      |                                      |
      |                                      jlong* {aka long long int*}
/mac/home/IdeaProjects/INTJers/jxtp/cpp/src/jxtp.cpp:26517:38: error: ‘jarr3’ was not declared in this scope; did you mean ‘jarg3’?
26517 |   SWIG_JavaArrayArgoutLonglong(jenv, jarr3, (long long *)arg3, jarg3);
      |                                      ^~~~~
      |                                      jarg3
/mac/home/IdeaProjects/INTJers/jxtp/cpp/src/jxtp.cpp:26518:38: error: ‘jarr6’ was not declared in this scope; did you mean ‘jarg6’?
26518 |   SWIG_JavaArrayArgoutLonglong(jenv, jarr6, (long long *)arg6, jarg6);
      |                                      ^~~~~
      |                                      jarg6
/mac/home/IdeaProjects/INTJers/jxtp/cpp/src/jxtp.cpp:26520:43: warning: invalid conversion from ‘int64_t*’ {aka ‘long int*’} to ‘jlong*’ {aka ‘long long int*’} [-fpermissive]
26520 |     jenv->ReleaseLongArrayElements(jarg3, arg3, 0);
      |                                           ^~~~
      |                                           |
      |                                           int64_t* {aka long int*}
In file included from /mac/home/IdeaProjects/INTJers/jxtp/cpp/src/jxtp.cpp:179:
/mac/home/IdeaProjects/INTJers/jxtp/cpp/src/../include/linux/jni.h:1720:42: note:   initializing argument 2 of ‘void JNIEnv_::ReleaseLongArrayElements(jlongArray, jlong*, jint)’
 1720 |                                   jlong *elems,
      |                                   ~~~~~~~^~~~~
/mac/home/IdeaProjects/INTJers/jxtp/cpp/src/jxtp.cpp:26523:43: warning: invalid conversion from ‘int64_t*’ {aka ‘long int*’} to ‘jlong*’ {aka ‘long long int*’} [-fpermissive]
26523 |     jenv->ReleaseLongArrayElements(jarg6, arg6, 0);
      |                                           ^~~~
      |                                           |
      |                                           int64_t* {aka long int*}
In file included from /mac/home/IdeaProjects/INTJers/jxtp/cpp/src/jxtp.cpp:179:
/mac/home/IdeaProjects/INTJers/jxtp/cpp/src/../include/linux/jni.h:1720:42: note:   initializing argument 2 of ‘void JNIEnv_::ReleaseLongArrayElements(jlongArray, jlong*, jint)’
 1720 |                                   jlong *elems,
      |                                   ~~~~~~~^~~~~
make[2]: *** [src/CMakeFiles/jxtp.dir/build.make:76: src/CMakeFiles/jxtp.dir/jxtp.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:98: src/CMakeFiles/jxtp.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
cp: cannot stat 'build/lib/libjxtp.so': No such file or directory
set +v
请移除上面显示 error 的所有行数处的代码后（共4行），按任意键继

**Comment by RationalityFrontline** [comment]
Yes, these error messages are expected to show up. It's a problem related to swig type transformation. Currently, you have to manually remove the lines that show up in the error message (4 lines in total, they are all in file "jxtp.cpp"). After removing these error lines, press any key to continue, the build process should then go on successfully. The prompt message "请移除上面显示 error 的所有行数处的代码后（共4行），按任意键继" means what I say above.

**Comment by RationalityFrontline** [comment]
The error line numbers are: 26479, 26480, 26517, 26518.
They look like this:
```c++
  SWIG_JavaArrayArgoutLonglong(jenv, jarr3, (long long *)arg3, jarg3); 
  SWIG_JavaArrayArgoutLonglong(jenv, jarr6, (long long *)arg6, jarg6); 
```

**Comment by RationalityFrontline** [comment]
Sorry I forget something. After building native cpp libraries you will go on to the step of generating self-contained jar. Before doing this step, you have to modify the file "./java/build.gradle.kts" :
![image](https://user-images.githubusercontent.com/69410606/115502754-0068b680-a2a8-11eb-9b91-167eb08e1f58.png)

**Comment by RationalityFrontline** [comment]
The naming convention follows this:
```
/natives
  /linux_32
     libxxx[-vvv].so
  /linux_64
     libxxx[-vvv].so
  /osx_32
     libxxx[-vvv].dylib
  /osx_64
     libxxx[-vvv].dylib
  /osx_arm64
     libxxx[-vvv].dylib
  /windows_32
     xxx[-vvv].dll
  /windows_64
     xxx[-vvv].dll
  /aix_32
     libxxx[-vvv].so
     libxxx[-vvv].a
  /aix_64
     libxxx[-vvv].so
     libxxx[-vvv].a
```

**Comment by xiamubobby** [comment]
> The naming convention follows this:
> ```
> /natives
>   /linux_32
>      libxxx[-vvv].so
>   /linux_64
>      libxxx[-vvv].so
>   /osx_32
>      libxxx[-vvv].dylib
>   /osx_64
>      libxxx[-vvv].dylib
>   /osx_arm64 <<———✖
>      libxxx[-vvv].dylib
>   /windows_32
>      xxx[-vvv].dll
>   /windows_64
>      xxx[-vvv].dll
>   /aix_32
>      libxxx[-vvv].so
>      libxxx[-vvv].a
>   /aix_64
>      libxxx[-vvv].so
>      libxxx[-vvv].a
> ```

Won't be working on Apple M1 cause I don't own one...

**Comment by RationalityFrontline** [comment]
The self-contained jar can be a multi-release jar. If you have access to an Apple M1 machine, you can build the cpp library on that machine, then copy the generated .dylib to your ./lib_arm64/ directory. And modify the gradle build script to something like this:
```kotlin
        from("../lib") {
            include("*.dylib")
            into("natives/osx_64")
        }
        from("../lib_arm64") {
            include("*.dylib")
            into("natives/osx_arm64")
        }
```

**Comment by RationalityFrontline** [comment]
But I think the .dylib offered by XTP official team is only compatiable with osx_64. So making it working on apple m1 machine might not be possible.

**Comment by RationalityFrontline** [comment]
> But I think the .dylib offered by XTP official team is only compatiable with osx_64. So making it working on apple m1 machine might not be possible.

Maybe Rosetta 2 can do the job.

**Comment by RationalityFrontline** [comment]
With the release of version [2.2.27.4-1.1.0](https://github.com/RationalityFrontline/jxtp/releases/tag/2.2.27.4-1.1.0), mac is now supported. Related pull request: #2
